### ISSUE TITLE
"constantly" in readme is not not necessary

### ISSUE THREAD

**Issue by vspinu** [weavejester/integrant-repl#6]
AFAICS  there is no need for constantly in prep reset. It could just be:

```clj
(integrant.repl/set-prep! config)
```

Why this prep step in the first place? I think it's confusing. Why not just have `(set-config! config)`?

**Comment by vspinu** [comment]
Oups, constantly is actually needed.  Sorry.

**Comment by weavejester** [comment]
The idea is that when you `reset` you want the configuration to be re-read, as it might have changed on disk. So `set-prep!` takes a zero-argument function that is re-evaluated after each reset. If this wasn't in place, Integrant-REPL wouldn't take into account changes to the configuration.

**Comment by vspinu** [comment]
I see. But would it be simpler if you could `(set-system! xyz)` where `xyz` could be either a 0-arg function or a map configuration?   Then init could do what prep does if xyz is a function. No need to expose an extra step.

Once we are on complexity topic, I would add here that using multiple namespace for such a simple utill library is an usability overkill. I often want to see/access the internals of the system. Now I have to import two namespaces:

```clj
   [integrant.repl :refer [go clear halt go init reset reset-all] :rename {go igo}]
   [integrant.repl.state :refer [system]]
```

All these kinda kill the benefits of this helper library. It looks to me that it's a bit too much hustle with small benefits over the plain `(init system)`/ `(halt system)`  workflow.

**Comment by weavejester** [comment]
It would be *easier* (as in more convenient) but not *simpler* (as in avoiding complexity).

The simplest thing is just to have one function with one behaviour, rather than one function with two behaviours. In this case, I don't think avoiding a `constantly` warrants introducing a new function.

Regarding the `integrant.repl.state` namespace, that was introduced to solve #4. There doesn't appear to be a way of just having one namespace, while also avoiding the issues with record reloading.
